Labb1_EF/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Labb1_EF.Data;
using Labb1_EF.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Labb1_EF.Models.ViewModels;

namespace Labb1_EF.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public EmployeesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: Employees
        public async Task<IActionResult> Index(int? id, int? leaveID)
        {

            var admin = (await _userManager
               .GetUsersInRoleAsync("Administrator"))
               .ToArray();

            var model = new AdminViewModel
            {
                Administrators = admin,
            };

            var viewModel = new EmployeeIndexData();
            viewModel.Employees = await _context.Employees
                .Include(e => e.LeaveApplications)
                .ThenInclude(e => e.LeaveTypes)
                .ToListAsync();

            if (id != null)
            {
                ViewData["EmployeeId"] = id.Value;
                Employee employee = viewModel.Employees.Where(
                    e => e.EmployeeId == id.Value).Single();
                viewModel.LeaveApplications = employee.LeaveApplications;
                
                if (employee.LeaveApplications == null || employee.LeaveApplications.Any())
                {
                    ViewData["Message"] = "No leave applications found for this employee";
                }
            }
            return View(viewModel);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FirstName,LastName,Email,DateOfHire,Salary,PersonalNumber,Gender,FK_PersonnelOfficeId")] Employee employee)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            //return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeeId,FirstName,LastName,Email,DateOfHire,Salary,PersonalNumber,Gender,FK_PersonnelOfficeId")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
          return (_context.Employees?.Any(e => e.EmployeeId == id)).GetValueOrDefault();
        }
    }
}

Labb1_EF/Controllers/LeaveApplicationListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Labb1_EF.Data;
using Labb1_EF.Models;
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.SqlClient;
using Labb1_EF.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Labb1_EF.Controllers
{
    [Authorize(Roles = "Employee, Administrator")]
    public class LeaveApplicationListsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public LeaveApplicationListsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            var emp = (await _userManager
              .GetUsersInRoleAsync("Employee"))
              .ToArray();

            var model = new AdminViewModel
            {
                Employees = emp,
            };

            var applicationDbContext = _context.LeaveApplications
                   .Include(la => la.Employees)
                   .Include(la => la.LeaveTypes);
 
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> filterApplications([Required] DateTime? searchStart, [Required] DateTime? searchEnd)
        {

            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Please choose a start and end date.";
                return RedirectToAction("Index"); // Redirect to the index action
            }

            ViewData["CurrentStartFilter"] = searchStart;
            ViewData["CurrentEndFilter"] = searchEnd;

            var applicationDbContext = _context.LeaveApplications
                .Include(la => la.Employees)
                .Include(la => la.LeaveTypes)
                .Where(la => la.CreatedAt >= searchStart && la.CreatedAt <= searchEnd);

            return View(await applicationDbContext.ToListAsync());

        }

        // GET: LeaveApplicationLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LeaveApplications == null)
            {
                return NotFound();
            }

            var leaveApplicationList = await _context.LeaveApplications
                .Include(l => l.Employees)
                .Include(l => l.LeaveTypes)
                .FirstOrDefaultAsync(m => m.LeaveApplicationListId == id);
            if (leaveApplicationList == null)
            {
                return NotFound();
            }

            return View(leaveApplicationList);
        }

        // GET: LeaveApplicationLists/Create
        public IActionResult Create()
        {
            ViewData["FK_EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "FullName");
            ViewData["FK_LeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeName");
            return View();
        }

        // POST: LeaveApplicationLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveApplicationListId,StartDate,EndDate,FK_EmployeeId,FK_LeaveTypeId")] LeaveApplicationList leaveApplicationList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leaveApplicationList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FK_EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "Email", leaveApplicationList.FK_EmployeeId);
            ViewData["FK_LeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeId", leaveApplicationList.FK_LeaveTypeId);
            return View(leaveApplicationList);
        }

        // GET: LeaveApplicationLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LeaveApplications == null)
            {
                return NotFound();
            }

            var leaveApplicationList = await _context.LeaveApplications.FindAsync(id);
            if (leaveApplicationList == null)
            {
                return NotFound();
            }
            ViewData["FK_EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "FullName", leaveApplicationList.FK_EmployeeId);
            ViewData["FK_LeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeName", leaveApplicationList.FK_LeaveTypeId);
            return View(leaveApplicationList);
        }

        // POST: LeaveApplicationLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveApplicationListId,StartDate,EndDate,FK_EmployeeId,FK_LeaveTypeId")] LeaveApplicationList leaveApplicationList)
        {
            if (id != leaveApplicationList.LeaveApplicationListId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveApplicationList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveApplicationListExists(leaveApplicationList.LeaveApplicationListId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FK_EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "Email", leaveApplicationList.FK_EmployeeId);
            ViewData["FK_LeaveTypeId"] = new SelectList(_context.LeaveTypes, "LeaveTypeId", "LeaveTypeId", leaveApplicationList.FK_LeaveTypeId);
            return View(leaveApplicationList);
        }

        // GET: LeaveApplicationLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LeaveApplications == null)
            {
                return NotFound();
            }

            var leaveApplicationList = await _context.LeaveApplications
                .Include(l => l.Employees)
                .Include(l => l.LeaveTypes)
                .FirstOrDefaultAsync(m => m.LeaveApplicationListId == id);
            if (leaveApplicationList == null)
            {
                return NotFound();
            }

            return View(leaveApplicationList);
        }

        // POST: LeaveApplicationLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LeaveApplications == null)
            {
                return Problem("Entity set 'ApplicationDbContext.LeaveApplications'  is null.");
            }
            var leaveApplicationList = await _context.LeaveApplications.FindAsync(id);
            if (leaveApplicationList != null)
            {
                _context.LeaveApplications.Remove(leaveApplicationList);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveApplicationListExists(int id)
        {
          return (_context.LeaveApplications?.Any(e => e.LeaveApplicationListId == id)).GetValueOrDefault();
        }
    }
}

Labb1_EF/Views/EmployeeInfo/Index.cshtml
@model IEnumerable<Labb1_EF.Models.EmployeeViewModel>
@{
    ViewData["Title"] = "Index";
}

<h3>Employees in Labb1_EF AB</h3>

<p>
    <a asp-controller="Employees" asp-action="Create">Add new employee</a> |
    <a asp-controller="LeaveApplicationLists" asp-action="index">Search applications by date</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
            @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.PersonalNumber)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.DateOfHire)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Salary)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderByDescending(e => e.CreatedAt).DistinctBy(e => e.EmployeeId))

        {
            string selectedRow = "";
            if (item.EmployeeId == (int?)ViewData["EmployeeId"])
            {
                selectedRow = "table-success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonalNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfHire)
                </td>
                <td>
                    @string.Format("{0:C}", item.Salary).Replace("$", "SEK")
                </td>
                <td>
                    <a asp-action="Index" asp-route-id="@item.EmployeeId">Select</a> |
                    <a asp-controller="Employees" asp-action="Edit" asp-route-id="@item.EmployeeId">Edit</a> |
                    <a asp-controller="Employees" asp-action="Details" asp-route-id="@item.EmployeeId">Details</a> |
                    <a asp-controller="Employees" asp-action="Delete" asp-route-id="@item.EmployeeId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewData["EmployeeId"] == null)
{
    <div class="alert alert-info" role="alert">Please select an employee to view their leave applications.</div>
}
else if (!Model.Any(l => l.EmployeeId == (int)ViewData["EmployeeId"]))

{
    <div class="alert alert-warning" role="alert">The selected employee has no leave applications.</div>
}
else
{
    <h3>Leave applications for selected employee:</h3>
    <table class="table bg-info rounded">
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().LeaveApplicationListId)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().StartDate)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().EndDate)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().CreatedAt)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().NumberOfDays)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().LeaveTypeName)</th>
        </tr>
        @foreach (var item in Model.Where(l => l.EmployeeId == (int)ViewData["EmployeeId"]).OrderByDescending(l => l.CreatedAt).DistinctBy(l => l.LeaveApplicationListId))

        {
            string selectedRow = "";
            if (item.LeaveApplicationListId == (int?)ViewData["EmployeeId"])
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @item.LeaveApplicationListId
                </td>
                <td>
                    @item.StartDate
                </td>
                <td>
                    @item.EndDate
                </td>
                <td>
                    @item.CreatedAt
                </td>
                <td>@item.NumberOfDays</td>
                <td>
                    @item.LeaveTypeName
                </td>
            </tr>
        }
    </table>
}